### ISSUE TITLE
little typo in midiMap.js 

### ISSUE THREAD

**Issue by sequethin** [johnbotris/maudio-oxygen-61-bitwig-script#1]
Someone had trouble in the Bitwig Discord because of this little bug - here's the smallest pull request I ever made lol https://github.com/sequethin/maudio-oxygen-61-bitwig-script/pull/1

**Comment by johnbotris** [comment]
How'd I manage to miss this :S but cheers!

**Comment by johnbotris** [comment]
eed345c1cd6f477590b1ee86085290e4e54b4387
